name: Deploy Frontend na EC2

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências e gerar build estático
        run: |
          npm install
          npm run build

      - name: Iniciar ssh-agent com chave de deploy
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.FRONTEND_DEPLOY_KEY }}

      - name: Sincronizar build com a EC2
        run: |
          rsync -avz --delete \
            ./out/ \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/frontend/

      - name: Recarregar Nginx na EC2
        run: |
          ssh -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
            "sudo systemctl reload nginx"
